const SUPABASE_URL="https://nzaazskskltxymloejft.supabase.co";
const SUPABASE_KEY="sb_publishable_p9a6zgEwrYnY99nsxdB7Mw_564Y4Rfj";
const sb=window.supabase?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;

const pages=document.querySelectorAll(".page");const navButtons=document.querySelectorAll("nav button");
function go(pageId){pages.forEach(page=>page.classList.toggle("active",page.id===pageId));navButtons.forEach(button=>button.classList.toggle("on",button.dataset.page===pageId));window.scrollTo(0,0);if(pageId==="takip"&&sb){sb.auth.getUser().then(({data:{user}})=>loadApplication(user));}if(pageId==="admin"&&sb){loadAdminPanel();}}
navButtons.forEach(button=>button.addEventListener("click",()=>go(button.dataset.page)));

const professions={
pflege:{title:"Pflegefachfrau / Pflegefachmann",desc:"Hastaneler, bakım merkezleri ve sağlık kuruluşlarında insanlara profesyonel bakım ve destek sunulan bir Ausbildung alanı.",duration:"Genellikle 3 yıl",language:"İşveren ve eyalete göre değişir",pay:"Kuruma ve toplu sözleşmeye göre değişir"},
kfz:{title:"Kfz-Mechatroniker/in",desc:"Araçların mekanik, elektronik ve dijital sistemlerinin bakım, arıza tespiti ve onarımı üzerine teknik bir Ausbildung.",duration:"Genellikle 3,5 yıl",language:"İşveren şartına göre değişir",pay:"İşveren ve eğitim yılına göre değişir"},
elektronik:{title:"Elektroniker/in",desc:"Elektrik sistemlerinin kurulumu, bakımı ve arıza giderme süreçlerinde çalışılan teknik bir meslek alanı.",duration:"Genellikle 3,5 yıl",language:"İşveren şartına göre değişir",pay:"Alan, işveren ve eğitim yılına göre değişir"},
hotel:{title:"Hotelfachfrau / Hotelfachmann",desc:"Otel işletmesinde misafir hizmetleri, rezervasyon, organizasyon ve farklı operasyon alanlarını kapsayan bir Ausbildung.",duration:"Genellikle 3 yıl",language:"Yoğun iletişim nedeniyle işveren şartı önemlidir",pay:"İşveren ve eğitim yılına göre değişir"},
lager:{title:"Fachkraft für Lagerlogistik",desc:"Ürün kabulü, depolama, sevkiyat hazırlığı ve lojistik süreçlerin düzenlenmesini kapsayan bir Ausbildung.",duration:"Genellikle 3 yıl",language:"İşveren şartına göre değişir",pay:"İşveren ve eğitim yılına göre değişir"},
anlagen:{title:"Anlagenmechaniker/in SHK",desc:"Isıtma, sıhhi tesisat ve iklimlendirme sistemlerinin kurulumu, bakımı ve onarımına odaklanan teknik Ausbildung.",duration:"Genellikle 3,5 yıl",language:"İşveren şartına göre değişir",pay:"İşveren ve eğitim yılına göre değişir"}};

function showProfession(key){const p=professions[key];const box=document.getElementById("profession-detail");if(!p||!box)return;box.hidden=false;box.innerHTML=`<div class="detail-top"><div><span class="eyebrow" style="color:var(--teal)">MESLEK DETAYI</span><h2>${p.title}</h2><p>${p.desc}</p></div><button class="detail-close" onclick="closeProfession()" aria-label="Kapat">×</button></div><div class="detail-facts"><div><small>Ausbildung süresi</small><b>${p.duration}</b></div><div><small>Almanca</small><b>${p.language}</b></div><div><small>Ausbildungsvergütung</small><b>${p.pay}</b></div></div><p class="detail-note">Kesin şartlar ve ücretler ilan, işveren, bölge ve eğitim yılına göre değişebilir.</p><button class="detail-apply" onclick="startApplication('${p.title.replace(/'/g,"\\'")}')">Bu meslek için başvur →</button>`;box.scrollIntoView({behavior:"smooth",block:"start"});}
function closeProfession(){const box=document.getElementById("profession-detail");if(box)box.hidden=true;}
function startApplication(title){go("basvuru");const heading=document.getElementById("application-title");const select=document.getElementById("profession-select");if(heading)heading.textContent=title+" için ön başvuru";if(select)select.value=title;}

if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));}
let deferredPrompt;const installButton=document.getElementById("install");window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredPrompt=event;if(installButton)installButton.hidden=false;});if(installButton)installButton.addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installButton.hidden=true;});window.addEventListener("appinstalled",()=>{deferredPrompt=null;if(installButton)installButton.hidden=true;});
const applicationForm=document.getElementById("application-form");
if(applicationForm){applicationForm.addEventListener("submit",async event=>{event.preventDefault();const message=document.getElementById("form-message");if(!sb){if(message){message.hidden=false;message.textContent="Bağlantı hazırlanamadı. Lütfen sayfayı yenile.";}return;}const {data:{user}}=await sb.auth.getUser();if(!user){if(message){message.hidden=false;message.textContent="Başvuruyu göndermek için önce Profil bölümünden kayıt ol veya giriş yap.";}go("profil");return;}const f=new FormData(applicationForm);const payload={user_id:user.id,full_name:f.get("fullName"),birth_year:Number(f.get("birthYear"))||null,city:f.get("city"),email:f.get("email"),phone:f.get("phone"),german_level:f.get("german"),education:f.get("education"),profession:f.get("profession"),cv_status:f.get("cv"),status:"pending",updated_at:new Date().toISOString()};const {error}=await sb.from("applications").insert(payload);if(message){message.hidden=false;message.textContent=error?"Başvuru gönderilemedi: "+error.message:"Başvurun başarıyla alındı. Sürecim bölümünden durumunu takip edebilirsin.";message.scrollIntoView({behavior:"smooth",block:"nearest"});}});}

async function refreshAuth(){if(!sb)return;const {data:{user}}=await sb.auth.getUser();const guest=document.getElementById("auth-guest"),logged=document.getElementById("auth-user"),email=document.getElementById("user-email"),account=document.getElementById("account-button");if(guest)guest.hidden=!!user;if(logged)logged.hidden=!user;if(email&&user)email.textContent=user.email;if(account)account.textContent=user?"Hesabım":"Giriş Yap";await checkAdmin(user);await loadApplication(user);}
async function loadApplication(user){const box=document.getElementById("application-status");if(!box)return;if(!user){box.innerHTML="<div class=\"panel-icon\">✓</div><div><h3>Başvuru bilgisi</h3><p>Durumunu görmek için hesabına giriş yap.</p></div>";return;}const {data,error}=await sb.from("applications").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1);if(error||!data||!data.length){box.innerHTML="<div class=\"panel-icon\">✓</div><div><h3>Henüz başvuru yok</h3><p>Başvuru formunu doldurduğunda durumun burada görünecek.</p></div>";return;}const x=data[0];const labels={pending:"Başvurun alındı",reviewing:"İnceleniyor",contacted:"İletişime geçildi",interview:"Görüşme aşamasında",contract:"Sözleşme aşamasında",completed:"Tamamlandı",rejected:"Sonuçlandı"};const status=labels[x.status]||"Başvurun işleniyor";const date=x.created_at?new Date(x.created_at).toLocaleDateString("tr-TR"):"—";box.innerHTML=`<div class="status-card"><div class="status-head"><div class="panel-icon">✓</div><div><small>GÜNCEL DURUM</small><h3>${status}</h3></div><span class="status-badge">${status}</span></div><div class="status-details"><div><small>Ausbildung</small><b>${x.profession||"Belirtilmedi"}</b></div><div><small>Başvuru tarihi</small><b>${date}</b></div><div><small>Almanca seviyesi</small><b>${x.german_level||"Belirtilmedi"}</b></div><div><small>Şehir</small><b>${x.city||"Belirtilmedi"}</b></div></div><div class="status-progress"><div class="status-line"><span class="done"></span><span></span><span></span><span></span></div><div class="status-labels"><b>Başvuru alındı</b><span>İnceleme</span><span>Görüşme</span><span>Sözleşme</span></div></div><p class="status-note">Başvurun Azubind sisteminde güvenli şekilde kayıtlı. Durum değiştiğinde bu ekran güncellenecek.</p></div>`;}
const authMessage=document.getElementById("auth-message");function showAuthMessage(t){if(authMessage){authMessage.hidden=false;authMessage.textContent=t;}}
document.querySelectorAll("[data-auth-tab]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-auth-tab]").forEach(x=>x.classList.toggle("on",x===b));document.getElementById("login-form").hidden=b.dataset.authTab!=="login";document.getElementById("signup-form").hidden=b.dataset.authTab!=="signup";if(authMessage)authMessage.hidden=true;}));
const loginForm=document.getElementById("login-form");if(loginForm)loginForm.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(loginForm);const {error}=await sb.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(error)showAuthMessage("Giriş yapılamadı: "+error.message);else{showAuthMessage("Giriş başarılı.");await refreshAuth();}});
const signupForm=document.getElementById("signup-form");if(signupForm)signupForm.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(signupForm);const {error}=await sb.auth.signUp({email:f.get("email"),password:f.get("password"),options:{emailRedirectTo:"https://app.azubind.com"}});showAuthMessage(error?"Kayıt oluşturulamadı: "+error.message:"Kayıt oluşturuldu. E-postana gelen doğrulama bağlantısına tıkla.");});
const logoutButton=document.getElementById("logout-button");if(logoutButton)logoutButton.addEventListener("click",async()=>{await sb.auth.signOut();await refreshAuth();});
if(sb){sb.auth.onAuthStateChange(()=>refreshAuth());refreshAuth();}

async function checkAdmin(user){const btn=document.getElementById("admin-button"),page=document.getElementById("admin");if(!user){if(btn)btn.hidden=true;if(page)page.hidden=true;return false;}const {data}=await sb.from("admins").select("user_id").eq("user_id",user.id).maybeSingle();const ok=!!data;if(btn)btn.hidden=!ok;if(page)page.hidden=!ok;return ok;}
const adminButton=document.getElementById("admin-button");if(adminButton)adminButton.addEventListener("click",()=>go("admin"));

async function loadAdminPanel(){
 const box=document.getElementById("admin-list");if(!box)return;
 const {data:{user}}=await sb.auth.getUser();if(!await checkAdmin(user)){go("profil");return;}
 box.innerHTML='<div class="panel"><div><h3>Başvurular yükleniyor...</h3></div></div>';
 const {data,error}=await sb.from("applications").select("*").order("created_at",{ascending:false});
 if(error){box.innerHTML='<div class="panel"><div><h3>Başvurular yüklenemedi</h3><p>'+safeText(error.message)+'</p></div></div>';return;}
 if(!data.length){box.innerHTML='<div class="panel"><div><h3>Henüz başvuru yok</h3></div></div>';return;}
 box.innerHTML=data.map(x=>'<article class="admin-card"><div><small>ADAY #'+x.id+'</small><h3>'+safeText(x.full_name||"İsimsiz aday")+'</h3><p>'+safeText(x.email||"E-posta yok")+' · '+safeText(x.phone||"Telefon yok")+'</p></div><div class="admin-facts"><span><small>Ausbildung</small><b>'+safeText(x.profession||"—")+'</b></span><span><small>Şehir</small><b>'+safeText(x.city||"—")+'</b></span><span><small>Almanca</small><b>'+safeText(x.german_level||"—")+'</b></span></div><label class="admin-status">Durum <select data-id="'+x.id+'"><option value="pending">Başvuru alındı</option><option value="reviewing">İnceleniyor</option><option value="contacted">İletişime geçildi</option><option value="interview">Görüşme aşamasında</option><option value="contract">Sözleşme aşamasında</option><option value="completed">Tamamlandı</option><option value="rejected">Sonuçlandı</option></select><em></em></label></article>').join("");
 data.forEach((x,i)=>{const s=box.querySelectorAll("select")[i];s.value=x.status||"pending";s.addEventListener("change",()=>saveAdminStatus(x.id,s));});
}
function safeText(v){const d=document.createElement("div");d.textContent=String(v);return d.innerHTML;}
async function saveAdminStatus(id,select){const note=select.parentElement.querySelector("em");select.disabled=true;note.textContent="Kaydediliyor...";const {error}=await sb.from("applications").update({status:select.value,updated_at:new Date().toISOString()}).eq("id",id);select.disabled=false;note.textContent=error?"Kaydedilemedi":"Kaydedildi ✓";}
